version: "3.7"

services:
  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    working_dir: /usr/src/app
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app
    expose:
      - "8000"
    command: "yarn dev"
    ports:
      - "8000:8000"
  app:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    working_dir: /build
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/build
    expose:
      - "3000"
    command: "yarn dev"
    ports:
      - "3000:3000"
    depends_on:
      - api